# Generated by Django 5.1.6 on 2025-02-11 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('category', models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('tech', 'Technology'), ('art', 'Art')], default='music', max_length=50)),
                ('image', models.ImageField(default='default_event.jpg', upload_to='event_images/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events_created', to=settings.AUTH_USER_MODEL)),
                ('rsvps', models.ManyToManyField(blank=True, related_name='rsvped_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
